import { Link } from 'react-router-dom';
import styled from 'styled-components';

// styled-components
const NavStyle = styled.nav`
  width: 800px;
  padding: 25px;

  display: grid;
  grid-template-columns: 9fr 1.6fr 1.4fr 0.8fr;

  background-color: #9f8473;
  color: white;
  font-size: 30px;
  font-weight: 700;

  font-family: 'Gowun Dodum', sans-serif;
  border-radius: 15px 15px 0 0;

  .fa-house {
    &:hover {
      animation: jello 0.8s ease-in-out infinite;
    }
  }
  .fa-heart {
    &:hover {
      animation: heartbeat 1s ease-in-out infinite;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-11-22 13:5:1
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation jello-horizontal
 * ----------------------------------------
 */
  @keyframes jello {
    0% {
      -webkit-transform: scale3d(1, 1, 1);
      transform: scale3d(1, 1, 1);
    }
    30% {
      -webkit-transform: scale3d(1.25, 0.75, 1);
      transform: scale3d(1.25, 0.75, 1);
    }
    40% {
      -webkit-transform: scale3d(0.75, 1.25, 1);
      transform: scale3d(0.75, 1.25, 1);
    }
    50% {
      -webkit-transform: scale3d(1.15, 0.85, 1);
      transform: scale3d(1.15, 0.85, 1);
    }
    65% {
      -webkit-transform: scale3d(0.95, 1.05, 1);
      transform: scale3d(0.95, 1.05, 1);
    }
    75% {
      -webkit-transform: scale3d(1.05, 0.95, 1);
      transform: scale3d(1.05, 0.95, 1);
    }
    100% {
      -webkit-transform: scale3d(1, 1, 1);
      transform: scale3d(1, 1, 1);
    }
  }
  @keyframes heartbeat {
    0% {
      transform: scale(1.1);
    }
    25% {
      transform: scale(0.9);
    }
    50% {
      transform: scale(1.1);
    }
    75% {
      transform: scale(0.9);
    }
    100% {
      transform: scale(1.1);
    }
  }
`;

const Narbar = () => {
  // !! link는 나중에 컴포넌트 만들면 수정할 것

  return (
    <NavStyle>
      <h1>🐹 오늘 뭐 하찍</h1>
      <Link to="/">
        <i className="fa-solid fa-house"></i>
      </Link>
      <Link to="/">
        <i className="fa-regular fa-calendar-days"></i>
      </Link>
      <Link to="/author">
        <i className="fa-solid fa-heart"></i>
      </Link>
    </NavStyle>
  );
};

export default Narbar;
